### ISSUE TITLE
Green checkmark

### ISSUE THREAD

**Issue by ItsNoted** [mat-sz/filedrop#35]
How can I get this to be a green checkmark? I followed the instructions. I didn't add any extra env variables and I am access it over https.

![Image](https://github.com/user-attachments/assets/3874db64-b257-4692-b898-4c9017fb3123)

**Comment by mat-sz** [comment]
Hey, you need to enable `WS_REQUIRE_CRYPTO` (if you're using the script, just pass `-s` as a parameter). This will only work over HTTPS though.

**Comment by ItsNoted** [comment]
> WS_REQUIRE_CRYPTO

I'm using Docker Compose from the repo. So change the "${REQUIRE_CRYPTO}" to -s?

```
version: '3'
services:
  filedrop:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - VITE_APP_NAME=${APP_NAME}
    environment:
      - WS_HOST=0.0.0.0
      - WS_APP_NAME=${APP_NAME}
      - WS_ABUSE_EMAIL=${ABUSE_EMAIL}
      - WS_USE_X_FORWARDED_FOR=${USE_X_FORWARDED_FOR}
      - WS_REQUIRE_CRYPTO=${REQUIRE_CRYPTO}
      - TURN_MODE=hmac
      - TURN_SERVER=turn:(hostname)
      - TURN_USERNAME=filedrop
      - TURN_SECRET=${TURN_SECRET}
    ports:
      - '${PORT}:5000'

  coturn:
    image: coturn/coturn
    command:
      - --log-file=stdout
      - --use-auth-secret
      - --static-auth-secret=${TURN_SECRET}
      - --no-multicast-peers
      - --no-tls
      - --no-dtls
      - --no-software-attribute
      - --fingerprint
      - --no-cli
    network_mode: host
    depends_on:
      - filedrop
```

**Comment by mat-sz** [comment]
Are you using the `docker-start.sh` script? If not, just start with `REQUIRE_CRYPTO=1 docker compose up --build`

**Comment by ItsNoted** [comment]
Keep getting `Bad Gateway`. when I change anything in the docker compose.

**Comment by mat-sz** [comment]
How did you start it for the first time then? Also, don't change the docker-compose.yml.

**Comment by ItsNoted** [comment]
I got it figured out. Is there a prebuilt image on ghcr or dockerhub? Or do you think this is the best way to deploy it?

**Comment by mat-sz** [comment]
There's no image, I just use the script.

**Comment by ItsNoted** [comment]
mmk.

**Comment by mat-sz** [comment]
I'll consider making a workflow to create the images though, since I have that working for Metastable already.

**Comment by ItsNoted** [comment]
I built my own image here:

itsnoted/filedrop

Use this compose:

```
services:
  filedrop:
    image: itsnoted/filedrop
    environment:
      - WS_HOST=0.0.0.0
      - WS_APP_NAME=${APP_NAME}
      - WS_ABUSE_EMAIL=${ABUSE_EMAIL}
      - WS_USE_X_FORWARDED_FOR=${USE_X_FORWARDED_FOR}
      - WS_REQUIRE_CRYPTO=1
      - TURN_MODE=hmac
      - TURN_SERVER=turn:(hostname)
      - TURN_USERNAME=filedrop
      - TURN_SECRET=${TURN_SECRET}
    ports:
      - '5000:5000'

  coturn:
    image: coturn/coturn
    command:
      - --log-file=stdout
      - --use-auth-secret
      - --static-auth-secret=${TURN_SECRET}
      - --no-multicast-peers
      - --no-tls
      - --no-dtls
      - --no-software-attribute
      - --fingerprint
      - --no-cli
    network_mode: host
    depends_on:
      - filedrop
 ```
